version: '3.3'

services:
  redmine:
    image: redmine
    env_file: "./mysql.env"
    restart: always
    ports:
      - "13000:3000"
  db:
    image: mysql:8.0
    #restart: always
    env_file: "./mysql.env"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '127.0.0.1:13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db:/var/lib/mysql
# Names our volume
volumes:
  db:
